@startuml

class Video_Frame{
}

class ROIed_Video_Frame{
}

Video_Frame <|-- ROIed_Video_Frame

abstract class Video_File{
}

class Video_Processor{
}

Video_File <|-- Video_Processor

class Realsense_Cam{
}

class Realsense_Cam_File_Wrapper{
}

Realsense_Cam *.. Realsense_Cam_File_Wrapper
Video_Processor <|-- Realsense_Cam_File_Wrapper

class Video_Cam_Procssor{
}

Realsense_Cam_File_Wrapper <|-- Video_Cam_Procssor
Video_Processor *.. Video_Cam_Procssor

abstract class Message{
}

class STOP_Message{
}

Message <|-- STOP_Message

class Frame_Data_Message{
}

Message <|-- Frame_Data_Message
Video_Frame *.. Frame_Data_Message

class Depth_Data_Message{
}

Message <|-- Depth_Data_Message

abstract class Module{
    {field} +Queue Tx
    {field} +Queue Rx
    {field} +Queue Stop_q
}

Message *.. Module

class Report_File{
}

class Data_Logger_Module{
}

Module <|-- Data_Logger_Module
Report_File *.. Data_Logger_Module
Depth_Data_Message *.. Data_Logger_Module

class Image_Processor_Handler{
}

Module <|-- Image_Processor_Handler
Video_File *.. Image_Processor_Handler
Frame_Data_Message *.. Image_Processor_Handler

@enduml